### ISSUE TITLE
Displays Host list but displays unknown in Country list

### ISSUE THREAD

**Issue by sderrick** [ip2location/ip2location_awstats#1]
Using BD1 database

Installed IP@Location plugin for awstats 7.8

Works fine in Host list, but displays Unknown Unknown in Domain/Country list?

![awstats-Screenshot](https://user-images.githubusercontent.com/729724/107991947-873da200-6f8c-11eb-954b-4d3de186c99e.png)

thanks,

Scott

**Comment by ip2location-com** [comment]
It's not related to this plugin. You need to enable DNS lookup to get the domain/hostname.

Please refer to https://awstats.sourceforge.io/docs/awstats_faq.html#DNS
